Args = --no-fallback \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=org.slf4j,ch.qos.logback \
       --initialize-at-run-time=io.netty.channel.DefaultFileRegion,io.netty.channel.epoll.Native,io.netty.channel.unix.Errors,io.netty.channel.unix.IovArray,io.netty.channel.unix.Socket,io.netty.channel.epoll.EpollEventArray,io.netty.channel.epoll.EpollEventLoop,io.netty.channel.epoll.Native \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       --allow-incomplete-classpath \
       --report-unsupported-elements-at-runtime
