package ai.kastrax.rag.document

import io.github.oshai.kotlinlogging.KotlinLogging
import io.ktor.client.*
import io.ktor.client.engine.cio.*
import io.ktor.client.plugins.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import org.dom4j.io.SAXReader
import java.io.ByteArrayInputStream
import java.io.StringReader
import java.net.URL
import java.util.regex.Pattern

private val logger = KotlinLogging.logger {}

/**
 * YouTube字幕文档加载器，从YouTube视频加载字幕作为文档。
 *
 * @property videoId YouTube视频ID
 * @property metadata 要添加到文档的元数据
 * @property language 字幕语言代码，默认为"en"（英语）
 * @property includeAutoGenerated 是否包含自动生成的字幕，默认为true
 * @property timeout 请求超时时间（毫秒），默认为30000
 */
class YouTubeSubtitleDocumentLoader(
    private val videoId: String,
    private val metadata: Map<String, Any> = emptyMap(),
    private val language: String = "en",
    private val includeAutoGenerated: Boolean = true,
    private val timeout: Long = 30000
) : DocumentLoader {

    companion object {
        /**
         * 从YouTube URL创建加载器。
         */
        fun fromUrl(
            videoUrl: String,
            metadata: Map<String, Any> = emptyMap(),
            language: String = "en",
            includeAutoGenerated: Boolean = true,
            timeout: Long = 30000
        ): YouTubeSubtitleDocumentLoader {
            return YouTubeSubtitleDocumentLoader(
                extractVideoId(videoUrl),
                metadata,
                language,
                includeAutoGenerated,
                timeout
            )
        }

        /**
         * 从YouTube URL中提取视频ID。
         */
        private fun extractVideoId(url: String): String {
            val patterns = listOf(
                Pattern.compile("(?<=v=)[a-zA-Z0-9_-]+"),
                Pattern.compile("(?<=youtu.be/)[a-zA-Z0-9_-]+"),
                Pattern.compile("(?<=embed/)[a-zA-Z0-9_-]+")
            )

            for (pattern in patterns) {
                val matcher = pattern.matcher(url)
                if (matcher.find()) {
                    return matcher.group()
                }
            }

            throw IllegalArgumentException("Invalid YouTube URL: $url")
        }
    }

    private val httpClient = HttpClient(CIO) {
        install(HttpTimeout) {
            requestTimeoutMillis = timeout
            connectTimeoutMillis = timeout
            socketTimeoutMillis = timeout
        }
    }

    override suspend fun load(): List<Document> {
        logger.debug { "Loading subtitles for YouTube video: $videoId" }

        return try {
            // 获取视频信息页面
            val videoUrl = "https://www.youtube.com/watch?v=$videoId"
            val response = httpClient.get(videoUrl)
            val html = response.bodyAsText()

            // 提取视频标题
            val title = extractVideoTitle(html)

            // 获取字幕轨道列表
            val captionTracks = extractCaptionTracks(html)

            if (captionTracks.isEmpty()) {
                logger.warn { "No caption tracks found for video: $videoId" }
                return emptyList()
            }

            // 选择合适的字幕轨道
            val selectedTrack = selectCaptionTrack(captionTracks, language, includeAutoGenerated)

            if (selectedTrack == null) {
                logger.warn { "No suitable caption track found for video: $videoId, language: $language" }
                return emptyList()
            }

            // 下载字幕内容
            val subtitleContent = downloadSubtitles(selectedTrack.url)

            // 解析字幕
            val subtitles = parseSubtitles(subtitleContent)

            if (subtitles.isEmpty()) {
                logger.warn { "Failed to parse subtitles for video: $videoId" }
                return emptyList()
            }

            // 构建文本内容
            val content = buildSubtitleContent(subtitles)

            // 基础元数据
            val baseMetadata = mutableMapOf(
                "source" to "youtube",
                "video_id" to videoId,
                "video_url" to videoUrl,
                "video_title" to (title ?: ""),
                "subtitle_language" to selectedTrack.languageCode,
                "subtitle_language_name" to selectedTrack.languageName,
                "subtitle_auto_generated" to selectedTrack.isAutoGenerated
            )

            // 合并用户提供的元数据
            val fullMetadata = baseMetadata + metadata

            listOf(Document(content, fullMetadata))
        } catch (e: Exception) {
            logger.error(e) { "Error loading subtitles for YouTube video: $videoId" }
            emptyList()
        } finally {
            httpClient.close()
        }
    }

    /**
     * 提取视频标题。
     */
    private fun extractVideoTitle(html: String): String? {
        val titlePattern = Pattern.compile("<title>(.+?) - YouTube</title>")
        val matcher = titlePattern.matcher(html)

        return if (matcher.find()) {
            matcher.group(1)
        } else {
            null
        }
    }

    /**
     * 提取字幕轨道列表。
     */
    private fun extractCaptionTracks(html: String): List<CaptionTrack> {
        val captionTracks = mutableListOf<CaptionTrack>()

        // 查找字幕轨道数据
        val captionPattern = Pattern.compile("\"captionTracks\":\\s*\\[(.+?)\\]")
        val matcher = captionPattern.matcher(html)

        if (matcher.find()) {
            val captionsJson = matcher.group(1)

            // 解析每个轨道
            val trackPattern = Pattern.compile("\\{(.+?)\\}")
            val trackMatcher = trackPattern.matcher(captionsJson)

            while (trackMatcher.find()) {
                val trackJson = trackMatcher.group(1)

                // 提取URL
                val urlPattern = Pattern.compile("\"baseUrl\":\\s*\"(.+?)\"")
                val urlMatcher = urlPattern.matcher(trackJson)

                // 提取语言代码
                val langCodePattern = Pattern.compile("\"languageCode\":\\s*\"(.+?)\"")
                val langCodeMatcher = langCodePattern.matcher(trackJson)

                // 提取语言名称
                val langNamePattern = Pattern.compile("\"name\":\\s*\\{\"simpleText\":\\s*\"(.+?)\"\\}")
                val langNameMatcher = langNamePattern.matcher(trackJson)

                // 检查是否是自动生成的
                val isAutoPattern = Pattern.compile("\"kind\":\\s*\"asr\"")
                val isAutoMatcher = isAutoPattern.matcher(trackJson)

                if (urlMatcher.find() && langCodeMatcher.find()) {
                    val url = urlMatcher.group(1).replace("\\u0026", "&")
                    val languageCode = langCodeMatcher.group(1)
                    val languageName = if (langNameMatcher.find()) langNameMatcher.group(1) else languageCode
                    val isAutoGenerated = isAutoMatcher.find()

                    captionTracks.add(
                        CaptionTrack(
                            url = url,
                            languageCode = languageCode,
                            languageName = languageName,
                            isAutoGenerated = isAutoGenerated
                        )
                    )
                }
            }
        }

        return captionTracks
    }

    /**
     * 选择合适的字幕轨道。
     */
    private fun selectCaptionTrack(
        tracks: List<CaptionTrack>,
        language: String,
        includeAutoGenerated: Boolean
    ): CaptionTrack? {
        // 首先尝试找到完全匹配的非自动生成字幕
        val exactMatch = tracks.find { it.languageCode == language && (!it.isAutoGenerated || includeAutoGenerated) }
        if (exactMatch != null) {
            return exactMatch
        }

        // 然后尝试找到语言代码前缀匹配的非自动生成字幕
        val prefixMatch = tracks.find {
            it.languageCode.startsWith(language) && (!it.isAutoGenerated || includeAutoGenerated)
        }
        if (prefixMatch != null) {
            return prefixMatch
        }

        // 如果允许自动生成的字幕，尝试找到完全匹配的自动生成字幕
        if (includeAutoGenerated) {
            val autoMatch = tracks.find { it.languageCode == language && it.isAutoGenerated }
            if (autoMatch != null) {
                return autoMatch
            }
        }

        // 如果没有找到匹配的，返回第一个可用的字幕（如果有的话）
        return tracks.firstOrNull { !it.isAutoGenerated || includeAutoGenerated }
    }

    /**
     * 下载字幕内容。
     */
    private suspend fun downloadSubtitles(url: String): String {
        val response = httpClient.get(url)
        return response.bodyAsText()
    }

    /**
     * 解析字幕内容。
     */
    private fun parseSubtitles(content: String): List<Subtitle> {
        val subtitles = mutableListOf<Subtitle>()

        try {
            val reader = SAXReader()
            val document = reader.read(StringReader(content))
            val root = document.rootElement

            // 解析每个文本元素
            root.elements("text").forEach { element ->
                val start = element.attributeValue("start")?.toDoubleOrNull() ?: 0.0
                val dur = element.attributeValue("dur")?.toDoubleOrNull() ?: 0.0
                val text = element.textTrim

                if (text.isNotEmpty()) {
                    subtitles.add(
                        Subtitle(
                            startTime = start,
                            duration = dur,
                            text = text
                        )
                    )
                }
            }
        } catch (e: Exception) {
            logger.error(e) { "Error parsing subtitles" }
        }

        return subtitles
    }

    /**
     * 构建字幕内容。
     */
    private fun buildSubtitleContent(subtitles: List<Subtitle>): String {
        val builder = StringBuilder()

        subtitles.forEach { subtitle ->
            val formattedTime = formatTime(subtitle.startTime)
            builder.append("[$formattedTime] ${subtitle.text}\n")
        }

        return builder.toString()
    }

    /**
     * 格式化时间。
     */
    private fun formatTime(seconds: Double): String {
        val hours = (seconds / 3600).toInt()
        val minutes = ((seconds % 3600) / 60).toInt()
        val secs = (seconds % 60).toInt()

        return String.format("%02d:%02d:%02d", hours, minutes, secs)
    }

    /**
     * 字幕轨道数据类。
     */
    private data class CaptionTrack(
        val url: String,
        val languageCode: String,
        val languageName: String,
        val isAutoGenerated: Boolean
    )

    /**
     * 字幕数据类。
     */
    private data class Subtitle(
        val startTime: Double,
        val duration: Double,
        val text: String
    )


}
