server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: kastrax-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
