Args = --initialize-at-build-time=kotlin \
       --report-unsupported-elements-at-runtime \
       --allow-incomplete-classpath \
       -H:+ReportExceptionStackTraces \
       -H:ReflectionConfigurationFiles=META-INF/native-image/reflection-config.json \
       -H:SerializationConfigurationResources=META-INF/native-image/serialization-config.json \
       -H:ResourceConfigurationFiles=META-INF/native-image/resource-config.json
