Args = --initialize-at-build-time=kotlin \
       --initialize-at-run-time=kotlin.reflect,kotlinx.serialization,ai.kastrax.integrations.deepseek.DeepSeekStreamChunk,kotlinx.serialization.json.Json,kotlinx.serialization.modules.SerializersModuleKt \
       --initialize-at-run-time=kotlin.jvm.internal.TypeParameterReference$Companion$WhenMappings \
       --report-unsupported-elements-at-runtime \
       --allow-incomplete-classpath \
       -H:+ReportExceptionStackTraces \
       -H:ReflectionConfigurationFiles=META-INF/native-image/reflection-config.json \
       -H:SerializationConfigurationResources=META-INF/native-image/serialization-config.json \
       -H:ResourceConfigurationFiles=META-INF/native-image/resource-config.json
